// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  header: string;
  headerContent: string;
  tabs: string;
}
export const cssExports: CssExports;
export default cssExports;
