// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bgBug': string;
  'bgDefault': string;
  'bgElectric': string;
  'bgFire': string;
  'bgGrass': string;
  'bgPink': string;
  'bgWater': string;
  'infoWrap': string;
  'label': string;
  'labelWrap': string;
  'pictureWrap': string;
  'root': string;
  'statItem': string;
  'statValue': string;
  'statWrap': string;
  'titleName': string;
}
export const cssExports: CssExports;
export default cssExports;
