// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'errorLabel': string;
  'root': string;
  'teamRocket': string;
  'wrapButton': string;
  'wrapContent': string;
  'wrapMainContent': string;
  'wrapMainText': string;
}
export const cssExports: CssExports;
export default cssExports;
